### ISSUE TITLE
failed stage resume: exception: $ operator made object too large

### ISSUE THREAD

**Issue by axinojolais** [juju/mgopurge#10] opened 2017-04-20 05:35 UTC
Hi,

I got the following today, on a server with 2GB RAM, 2GB swap, and 2.6M txns :
```
2017-04-19 13:12:06 Running stage "presence": Clear presence data. This will be recreated when the controllers restart.
2017-04-19 13:12:06 Running stage "purgemissing": Purge orphaned transactions
2017-04-19 13:13:25 Running stage "resume": Resume incomplete transactions
2017-04-19 19:42:59 failed stage resume: exception: $ operator made object too large
```

Also, when I run the "prune" stage, I get : 
```
2017-04-20 05:55:54 Running stage "prune": Prune finalised transactions
2017-04-20 05:55:54 buildInfo reported: [2 4 10 0]
2017-04-20 05:55:54 loading all completed transactions
2017-04-20 05:55:54 iterating the transactions collection to build the working set: "txns.prunetemp"
2017-04-20 05:56:35 cleanup of "txns.prunetemp" failed: ns not found
2017-04-20 05:56:35 failed stage prune: reading completed txns: exception: aggregation result exceeds maximum document size (16MB)
```

This is with mgopurge v1.4, juju 1.25.10 on xenial, mongod v2.4.10

**Comment by jameinel** [comment] 2017-04-20 06:23
Possibly addressed by https://github.com/juju/txn/pull/31 we'll want to land that in juju/txn and then merge it into mgopurge for 1.5

**Comment by mjs** [comment] 2017-05-17 23:49
mgopurge 1.5 is out. This should fix this issue.

**Closed by mjs** 2017-05-17 23:49 UTC

**Comment by msplival** [comment] 2017-06-05 11:20
I am running mgopurge on customer's database, using latest mogopurge (release version, 1.5), and I'm hitting this error:

mario@rotom:~/tools$ ./mgopurge -password XXXXXXX -username machine-2
This program should only be used to recover from specific transaction
related problems in a Juju database. Casual use is strongly
discouraged. Irreversible damage may be caused to a Juju deployment
through improper use of this tool.

Aside from limited cases, this program should not be run while Juju
controller machine agents are running.

Ok to proceed? [y/n] y
2017-06-05 11:04:23 Running stage "presence": Clear presence data. This will be recreated when the controllers restart.
2017-06-05 11:04:23 Running stage "purgemissing": Purge orphaned transactions
2017-06-05 11:05:44 Running stage "resume": Resume incomplete transactions
2017-06-05 11:08:32 failed stage resume: exception: $ operator made object too large
mario@rotom:~/tools$

**Comment by jameinel** [comment] 2017-06-05 11:52
I'm assuming this is a Mongo 2.4 (Juju 1.x) database?
I thought the fix for operator too large was in 1.5. Can you confirm you're
running the right binary? Can you run mgopurge --version

John
=:->

**Comment by jameinel** [comment] 2017-06-05 11:54
Hm... Resume failing is surprising as well. One thing you could try is to
just run -stages prune first, which is the stage that can be run live and
then following up with a deeper scan. "prune" won't fix corruption but it
does clean out the bulk of the transactions if they are all completed.
(resume is run first because it moves more txn through to completed so they
can be cleaned by prune)

John
=:->

**Comment by msplival** [comment] 2017-06-05 12:18
Hi, John. 

Yes, this is mgopurge v1.5 running against mongo 2.4 (juju 1.25.10). I did run just 'prune' and it completed without an issues. However, running 'compact' from mgopurge failed (not sure why, though) so I run it manually (db.repairDatabase()). 

I am re-running mgopurge now (without -stage) - before the 'resume' stage failed cca 3 minutes after it started, but now it's running for almost 15 minutes - I have started mongod with -vvv so I see all the write queries against the database and although mgopurge is consuming 100% of CPU time, I don't see any traffic against the database.

I'll leave it running and report back here the progress.

**Comment by jameinel** [comment] 2017-06-05 13:07
If the first step noticed that there were missing transactions, it is
possible that you have a document with lots of "prepared but not applied"
transactions. The Resume step can be O(N^2) on a queue of transactions to
be applied. Some people have seen 100,000s of transactions in a single
document which would end up taking ~24hrs to apply. I've been working on
detecting and working around those cases.

Do you have a copy of the original database? (The one that failed the
initial Resume).

Ah, you know what, its possible that Resume is failing because applying a
transaction (moving it from preparing to prepared) would make the document
too big. That sounds likely that you would end up in the case where Resume
just can't make progress. :(

John
=:->

**Comment by msplival** [comment] 2017-06-05 14:21
I do have the copy of the original database. 

The txns collection is still cca 800MB large, and it still contains 1620314 documents (after all the stages, except 'resume' have been run).

So, yes, the 'resume' is going to take very long time now - it's been running for cca hour and a half now and it went trough only 104000 transactions. I will leave it running to see if additional space can be freed.

Mario

**Comment by msplival** [comment] 2017-06-09 09:35
So, the mgopurge finally finished, and it took almost three days to complete:

http://paste.ubuntu.com/24814372/

Now, the 'resume' stage took unusually long - I see that this is actually a problem with txn.NewRunner, rather than with mgopurge itself.

However! Based on my past discussion with Menno, I remembered that for whatever reason juju sometimes leaves a lot of transactions in 'preparing' state. Verifying this, it looks like more than half of transactions are like that (this is from fresh database, before mgopurge was run):
> db.txns.find().count()
2142677
> db.txns.find({"s":1}).count()
1253136

Now, I checked the database after mgopurge tool was run (that 3 day-long run) and here are counts:
> db.txns.find().count()
1253201
> db.txns.find({"s":1}).count()
1253128

So, while the number of the transactions halved there is still a lot of {"s":1} transactions - which, if I understood correctly, are 'preparing' transactions, which are ignored by juju. 
I just deleted them manually from a 'clean' (un-mgopurged) database and I am running mgopurge again. I expect that 'resume' stage will be significantly faster, but my question here is are those {"s":1} transactions ok to remove?

Regards, Mario

P.S. Should we move this discussion under a new issue?

**Comment by jameinel** [comment] 2017-06-09 11:42
the resume stage is supposed to handle 'preparing txns:
http://bazaar.launchpad.net/+branch/mgo/v2/view/head:/txn/txn.go#L315

(source has moved but It still looks like that).

if you still have preparing left behind then it's something we should
investigate.

deleting them can lead to the issues around "cannot find txn" as there
could be a doc that has been updated.

John
=:->

**Comment by msplival** [comment] 2017-06-12 13:15
2017-06-09 09:23:02 Running stage "resume": Resume incomplete transactions
2017-06-11 20:47:02 Running stage "prune": Prune finalised transactions


This is the run-time after I removed 'preparing' transactions from the database, so it is a improvement, but it still takes forever :)

So, yes, I can confirm that there are still 'preparing' ones left.
